Name: ${CPACK_PACKAGE_NAME}
Description: ${CPACK_PACKAGE_DESCRIPTION_SUMMARY}
Version: ${CPACK_PACKAGE_VERSION}
prefix=${CPACK_PACKAGING_INSTALL_PREFIX}
includedir=${CPACK_PACKAGE_INCLUDE_DIR}
libdir=${CPACK_PACKAGE_LIB_DIR}
Libs: ${CPACK_PACKAGE_CONFIG_LIBS}
Cflags: ${CPACK_PACKAGE_CONFIG_CFLAGS}
